epicsEnvSet "LOOKUP_SMC300_01" "$(ICPCONFIGROOT)/motionSetPoints/sample.txt"

#epicsEnvSet "LOOKUP_SMC300_01" "$(ICPCONFIGROOT)/motionSetPoints/sample1D.txt"


motionSetPointsConfigure("LOOKUP_SMC300_01","LOOKUP_SMC300_01")


dbLoadRecords("$(MOTIONSETPOINTS)/db/motionSetPoints.db","P=$(MYPVPREFIX)LKUP:SAMPLE:,NAME1=Linear,AXIS1=$(MYPVPREFIX)MOT:SAMPLE:LIN,NAME2=Rotational,AXIS2=$(MYPVPREFIX)MOT:SAMPLE:ROT,TOL=1,LOOKUP=LOOKUP_SMC300_01")
dbLoadRecords("$(MOTOR)/db/SM300_extra.db","P=$(MYPVPREFIX)LKUP:SAMPLE:DEV:,$(IFIOC)= ,PVPREFIX=$(MYPVPREFIX), PORT=$(AMOTOR), ADDR=0")
