# Look up file location
$(IFDMC06) epicsEnvSet "LOOKUPFILE1" "$(ICPCONFIGROOT)/motionSetPoints/monitor3.txt"
$(IFDMC05) epicsEnvSet "LOOKUPFILE3" "$(ICPCONFIGROOT)/motionSetPoints/sample_larmor.txt"

# Create lookup file controller
$(IFDMC06) motionSetPointsConfigure("LOOKUPFILE1","LOOKUPFILE1")
$(IFDMC05) motionSetPointsConfigure("LOOKUPFILE3","LOOKUPFILE3")

# 1D motion setpoints based on a motor
$(IFDMC06) dbLoadRecords("$(MOTIONSETPOINTS)/db/motionSetPoints.db","P=$(MYPVPREFIX)LKUP:MON3:,TARGET_PV1=$(MYPVPREFIX)MOT:MTR0601,TARGET_RBV1=$(MYPVPREFIX)MOT:MTR0601.RBV,TARGET_DONE=$(MYPVPREFIX)MOT:MTR0601.DMOV,TOL=1,LOOKUP=LOOKUPFILE1")

# 2D motion setpoints based on a motors, NB the second motor is actually from an axis but the motion setpoint is using it like a motor
$(IFDMC05) dbLoadRecords("$(MOTIONSETPOINTS)/db/motionSetPoints.db","P=$(MYPVPREFIX)LKUP:SAMPLE_LARMOR:,TARGET_PV1=$(MYPVPREFIX)MOT:MTR0703,TARGET_RBV1=$(MYPVPREFIX)MOT:MTR0703.RBV,TARGET_DONE=$(MYPVPREFIX)MOT:MTR0703.DMOV,TARGET_PV2=$(MYPVPREFIX)MOT:STACK:ZLO:MTR,TARGET_RBV2=$(MYPVPREFIX)MOT:STACK:ZLO:MTR.RBV,TARGET_DONE2=$(MYPVPREFIX)MOT:STACK:ZLO:MTR.DMOV,TOL=1,LOOKUP=LOOKUPFILE3")
