# $(ICPCONFIGDIR) or $(ICPCONFIGROOT) ?
$(IFIOC_GALIL_06) epicsEnvSet "LOOKUPFILE2" "$(MOTIONSETPOINTS)/settings/setting_for_system_tests/instrument_scripts/larmor/monitor4.txt"
$(IFIOC_GALIL_05) epicsEnvSet "LOOKUPFILE3" "$(MOTIONSETPOINTS)/settings/setting_for_system_tests/instrument_scripts/larmor/sample.txt"


$(IFIOC_GALIL_06) motionSetPointsConfigure("LOOKUPFILE2","LOOKUPFILE2", 1)
$(IFIOC_GALIL_05) motionSetPointsConfigure("LOOKUPFILE3","LOOKUPFILE3", 2)


$(IFIOC_GALIL_06) dbLoadRecords("$(MOTIONSETPOINTS)/db/motionSetPointsSingleAxis.db","P=$(MYPVPREFIX)LKUP:MON4:,AXIS0=$(MYPVPREFIX)MOT:MON:4,TOL=1,LOOKUP=LOOKUPFILE2")

# The two lines below control which axis is used for the translation of the sample changer MOT:STACK:Y or MOT:SAMP:CHANG. Comment or uncomment as required.
#$(IFIOC_GALIL_05) dbLoadRecords("$(MOTIONSETPOINTS)/db/motionSetPointsDoubleAxis.db","P=$(MYPVPREFIX)LKUP:SAMPLE:,AXIS0=$(MYPVPREFIX)MOT:STACK:Y,AXIS1=$(MYPVPREFIX)MOT:STACK:ZLO,TOL=1,LOOKUP=LOOKUPFILE3")
$(IFIOC_GALIL_05) dbLoadRecords("$(MOTIONSETPOINTS)/db/motionSetPointsDoubleAxis.db","P=$(MYPVPREFIX)LKUP:SAMPLE:,AXIS0=$(MYPVPREFIX)MOT:SAMP:CHANG,AXIS1=$(MYPVPREFIX)MOT:STACK:ZLO,TOL=1,LOOKUP=LOOKUPFILE3")


$(IFIOC_GALIL_06) dbLoadRecordsLoop("$(MOTIONSETPOINTS)/db/inPos.db","P=$(MYPVPREFIX)LKUP:MON4:,AXIS0=$(MYPVPREFIX)MOT:MON:4,TOL=1,LOOKUP=LOOKUPFILE2","NUMPOS", 0, 30)
#$(IFIOC_GALIL_05) dbLoadRecordsLoop("$(MOTIONSETPOINTS)/db/inPos.db","P=$(MYPVPREFIX)LKUP:SAMPLE:,AXIS0=$(MYPVPREFIX)MOT:STACK:Y,AXIS1=$(MYPVPREFIX)MOT:STACK:ZLO,TOL=1,LOOKUP=LOOKUPFILE3","NUMPOS", 0, 30)
$(IFIOC_GALIL_05) dbLoadRecordsLoop("$(MOTIONSETPOINTS)/db/inPos.db","P=$(MYPVPREFIX)LKUP:SAMPLE:,AXIS0=$(MYPVPREFIX)MOT:SAMP:CHANG,AXIS1=$(MYPVPREFIX)MOT:STACK:ZLO,TOL=1,LOOKUP=LOOKUPFILE3","NUMPOS", 0, 30)
